language: node_js
node_js: 4.2.4
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
install:
    - cd server && npm install && cd ..
    - cd kana && npm install && cd ..
script:
    - cd server && npm test && cd ..
    - cd kana && npm test && cd ..