language: node_js
node_js: 4.2.4
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
    - cd server && npm install && npm run build && cd ..
    - cd kana && npm install && cd ..
    - cd client && npm install && cd ..
script:
    - cd server && npm test && cd ..
    - cd kana && npm test && cd ..