'use strict';

module.exports = [
    'a', 'i', 'u', 'e', 'o',
    'ka', 'ki', 'ku', 'ke', 'ko',
    'kya', 'kyu', 'kyo',
    'ga', 'gi', 'gu', 'ge', 'go',
    'gya', 'gyu', 'gyo',
    'sa', 'si', 'su', 'se', 'so',
    'sya', 'syu', 'syo',
    'za', 'zi', 'zu', 'ze', 'zo',
    'zya', 'zyu', 'zyo',
    'ta', 'ti', 'tu', 'te', 'to',
    'tya', 'tyu', 'tyo',
    'da', 'de', 'do',
    'na', 'ni', 'nu', 'ne', 'no',
    'nya', 'nyu', 'nyo',
    'ha', 'hi', 'hu', 'he', 'ho',
    'hya', 'hyu', 'hyo',
    'pa', 'pi', 'pu', 'pe', 'po',
    'pya', 'pyu', 'pyo',
    'ba', 'bi', 'bu', 'be', 'bo',
    'bya', 'byu', 'byo',
    'ma', 'mi', 'mu', 'me', 'mo',
    'mya', 'myu', 'myo',
    'ya', 'yu', 'yo',
    'ra', 'ri', 'ru', 're', 'ro',
    'rya', 'ryu', 'ryo',
    'wa', 'wo',
    'n',
];